### ISSUE TITLE
[Question] Windows supported?

### ISSUE THREAD

**Issue by tan-wei** [socketry/lightio#15]
- OS: WInsows 10
- Ruby: 2.5.5 x32

It fails after `require 'lightio'`, error messages are shown below:
```
ArgumentError: unsupported backend:
from C:/Ruby25/lib/ruby/gems/2.5.0/gems/nio4r-2.3.1/lib/nio/selector.rb:17:in `initialize'
Caused by LoadError: cannot load such file -- lightio
from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```
It seems `nio4r` is selected as the backends.

**Comment by tan-wei** [comment]
Maybe I should set the backend in ENV just like
```bat
set LIGHTIO_BACKEND=epoll
```
How to set the backend with an available one? Thanks!

**Comment by tan-wei** [comment]
It seems that the only valid input for `NIO::Selector.new` is `:ruby` (a symbol but not a string). When I set `LIGHTIO_BACKEND` in `ENV`, it is always a string. For example, when I set LIGHTIO_BACKEND to `ruby`, it will also fail.
